# Generated by Django 5.1.7 on 2025-04-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("company_website", models.URLField(blank=True, null=True)),
                ("industry", models.CharField(max_length=100)),
                ("company_size", models.CharField(max_length=50)),
                ("challenges", models.TextField()),
                ("needs_website", models.BooleanField(default=False)),
                ("needs_app", models.BooleanField(default=False)),
                ("for_learning", models.BooleanField(default=False)),
                ("agreed_to_terms", models.BooleanField(default=False)),
                ("wants_updates", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
