# Generated by Django 5.2.6 on 2026-03-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=20)),
                ('logger', models.CharField(db_index=True, max_length=255)),
                ('message', models.TextField()),
                ('exception', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='auth_app_sy_timesta_969b36_idx'), models.Index(fields=['level', '-timestamp'], name='auth_app_sy_level_4eaa93_idx')],
            },
        ),
    ]
