# Generated by Django 5.2.6 on 2026-03-04 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_systemlog'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='systemlog',
            name='auth_app_sy_timesta_969b36_idx',
        ),
        migrations.RemoveIndex(
            model_name='systemlog',
            name='auth_app_sy_level_4eaa93_idx',
        ),
    ]
